import { db } from "./index";
import { resources, categories } from "./schema";

const seedCategories = [
  { name: "DevOps", slug: "devops", icon: "Settings" },
  { name: "Cloud Computing", slug: "cloud", icon: "Cloud" },
  { name: "Platform Engineering", slug: "platform-engineering", icon: "Layers" },
  { name: "Kubernetes", slug: "kubernetes", icon: "Box" },
  { name: "AI Engineering", slug: "ai-engineering", icon: "Cpu" },
  { name: "Cybersecurity", slug: "cybersecurity", icon: "Shield" },
  { name: "SRE", slug: "sre", icon: "Activity" },
  { name: "GitOps", slug: "gitops", icon: "GitBranch" },
  { name: "Linux", slug: "linux", icon: "Terminal" },
  { name: "Networking", slug: "networking", icon: "Globe" },
  { name: "CI/CD", slug: "cicd", icon: "Zap" },
];

const seedResources = [
  {
    title: "The Roadmap to DevOps in 2024",
    description: "A comprehensive guide on how to become a DevOps engineer in 2024 with a clear learning path.",
    url: "https://roadmap.sh/devops",
    type: "documentation",
    category: "DevOps",
    platform: "Roadmap.sh",
    tags: "roadmap,learning,devops",
    upvotes: 1250,
    isFree: true,
    rating: 5,
    isFeatured: true,
  },
  {
    title: "Kubernetes Documentation",
    description: "Official documentation for Kubernetes orchestration system.",
    url: "https://kubernetes.io/docs/home/",
    type: "documentation",
    category: "Kubernetes",
    platform: "Kubernetes",
    tags: "k8s,orchestration,containers",
    upvotes: 850,
    isFree: true,
    rating: 5,
  },
  {
    title: "Awesome Platform Engineering",
    description: "A curated list of platform engineering resources, tools, and tutorials.",
    url: "https://github.com/platform-engineering-org/awesome-platform-engineering",
    type: "repository",
    category: "Platform Engineering",
    platform: "GitHub",
    tags: "platform,engineering,awesome",
    upvotes: 450,
    isFree: true,
    rating: 4,
  },
  {
    title: "AWS Workshops",
    description: "Self-paced labs and workshops for learning AWS services.",
    url: "https://workshops.aws/",
    type: "course",
    category: "Cloud Computing",
    platform: "AWS",
    tags: "aws,cloud,labs",
    upvotes: 620,
    isFree: true,
    rating: 5,
  },
  {
    title: "Hussein Nasser's Backend Engineering",
    description: "In-depth videos on backend engineering, networking, and cloud architecture.",
    url: "https://www.youtube.com/@hnasser",
    type: "video",
    category: "DevOps",
    platform: "YouTube",
    tags: "backend,networking,cloud",
    upvotes: 980,
    isFree: true,
    rating: 5,
    isFeatured: true,
  },
  {
    title: "Terraform Best Practices",
    description: "Guide on how to structure your Terraform projects for production.",
    url: "https://www.terraform-best-practices.com/",
    type: "documentation",
    category: "DevOps",
    platform: "Terraform",
    tags: "iac,terraform,infrastructure",
    upvotes: 340,
    isFree: true,
    rating: 4,
  },
  {
    title: "Google SRE Book",
    description: "The original Site Reliability Engineering book by Google engineers.",
    url: "https://sre.google/sre-book/table-of-contents/",
    type: "blog",
    category: "SRE",
    platform: "Google",
    tags: "sre,reliability,operations",
    upvotes: 1500,
    isFree: true,
    rating: 5,
    isFeatured: true,
  },
  {
    title: "LangChain Documentation",
    description: "Learn how to build LLM-powered applications.",
    url: "https://python.langchain.com/docs/get_started/introduction",
    type: "documentation",
    category: "AI Engineering",
    platform: "LangChain",
    tags: "ai,llm,python",
    upvotes: 720,
    isFree: true,
    rating: 4,
  },
  {
    title: "Docker Curriculum",
    description: "A comprehensive tutorial on getting started with Docker and containers.",
    url: "https://docker-curriculum.com/",
    type: "documentation",
    category: "DevOps",
    platform: "Docker Curriculum",
    tags: "docker,containers,beginner",
    upvotes: 890,
    isFree: true,
    rating: 5,
  },
  {
    title: "Full Stack Open - CI/CD",
    description: "A great course on CI/CD pipelines, GitHub Actions, and deployment.",
    url: "https://fullstackopen.com/en/part11",
    type: "course",
    category: "GitOps",
    platform: "University of Helsinki",
    tags: "cicd,github-actions,automation",
    upvotes: 1100,
    isFree: true,
    rating: 5,
  },
  {
    title: "Cloud Native Computing Foundation (CNCF) Landscape",
    description: "The complete map of the cloud native ecosystem.",
    url: "https://landscape.cncf.io/",
    type: "documentation",
    category: "Cloud Computing",
    platform: "CNCF",
    tags: "cloud-native,landscape,k8s",
    upvotes: 430,
    isFree: true,
    rating: 4,
  },
  {
    title: "The Linux Command Line",
    description: "A complete introduction to the Linux shell and command line.",
    url: "https://linuxcommand.org/",
    type: "documentation",
    category: "DevOps",
    platform: "LinuxCommand.org",
    tags: "linux,bash,shell",
    upvotes: 1200,
    isFree: true,
    rating: 5,
  },
  {
    title: "AWS Announces New Generative AI Capabilities for Amazon Bedrock",
    description: "Amazon Bedrock now includes new models and features to help customers build and scale generative AI applications more easily.",
    url: "https://aws.amazon.com/blogs/aws/new-generative-ai-capabilities-for-amazon-bedrock/",
    type: "news",
    category: "AI Engineering",
    platform: "AWS Blog",
    author: "Jeff Barr",
    tags: "aws,ai,bedrock",
    upvotes: 450,
  },
  {
    title: "Kubernetes 1.30: Uwubernetes",
    description: "The latest release of Kubernetes brings enhancements to structured logging, node memory swapping, and more.",
    url: "https://kubernetes.io/blog/2024/04/17/kubernetes-v1-30-release/",
    type: "news",
    category: "Kubernetes",
    platform: "Kubernetes Blog",
    author: "Release Team",
    tags: "k8s,release",
    upvotes: 890,
  },
  {
    title: "Terraform 1.8 Adds Provider-Defined Functions",
    description: "HashiCorp announces Terraform 1.8 with a major new feature: functions defined by providers.",
    url: "https://www.hashicorp.com/blog/terraform-1-8-adds-provider-defined-functions",
    type: "news",
    category: "DevOps",
    platform: "HashiCorp Blog",
    author: "Terraform Team",
    tags: "terraform,iac",
    upvotes: 670,
  },
  {
    title: "Google Cloud introduces AI-powered security operations",
    description: "New capabilities in Google Cloud Security Operations use generative AI to help security teams detect and respond to threats faster.",
    url: "https://cloud.google.com/blog/products/identity-security/introducing-ai-powered-security-operations",
    type: "news",
    category: "Cybersecurity",
    platform: "Google Cloud Blog",
    author: "Security Team",
    tags: "gcp,security,ai",
    upvotes: 320,
  },
  {
    title: "Microsoft Azure announces Cobalt 100 CPUs for general availability",
    description: "Azure's first custom-built processors are now available for customers, offering better price-performance for cloud workloads.",
    url: "https://azure.microsoft.com/en-us/blog/azure-cobalt-100-cpus-now-generally-available/",
    type: "news",
    category: "Cloud Computing",
    platform: "Azure Blog",
    author: "Azure Team",
    tags: "azure,hardware,cloud",
    upvotes: 510,
  },
  {
    title: "Docker Desktop 4.30 includes Docker Build Cloud integration",
    description: "The latest version of Docker Desktop makes it easier to use remote build capabilities for faster container image creation.",
    url: "https://www.docker.com/blog/docker-desktop-4-30-docker-build-cloud/",
    type: "news",
    category: "DevOps",
    platform: "Docker Blog",
    author: "Docker Team",
    tags: "docker,containers",
    upvotes: 410,
  },
  {
    title: "OpenAI launches SearchGPT, a prototype of new AI search features",
    description: "OpenAI is testing a new AI-powered search engine that aims to give users fast and timely answers with clear and relevant sources.",
    url: "https://openai.com/index/searchgpt-prototype/",
    type: "news",
    category: "AI Engineering",
    platform: "OpenAI Blog",
    author: "OpenAI",
    tags: "ai,search,searchgpt",
    upvotes: 1200,
  },
  {
    title: "The Case for Platform Engineering in 2024",
    description: "Why organizations are moving away from traditional DevOps towards internal developer platforms.",
    url: "https://techcrunch.com/2024/05/20/platform-engineering-is-the-new-devops/",
    type: "news",
    category: "Platform Engineering",
    platform: "TechCrunch",
    author: "Ron Miller",
    tags: "platform-engineering,devops",
    upvotes: 950,
  },
  {
    title: "Anthropic's Claude 3.5 Sonnet sets new industry benchmarks",
    description: "The latest model from Anthropic outperforms competitors in coding, reasoning, and visual processing tasks.",
    url: "https://www.anthropic.com/news/claude-3-5-sonnet",
    type: "news",
    category: "AI Engineering",
    platform: "Anthropic",
    author: "Anthropic Team",
    tags: "ai,llm,claude",
    upvotes: 1500,
  }
];

async function seed() {
  console.log("Seeding data...");
  
  for (const cat of seedCategories) {
    await db.insert(categories).values(cat).onConflictDoNothing();
  }

  for (const res of seedResources) {
    await db.insert(resources).values(res).onConflictDoNothing();
  }

  console.log("Seeding completed!");
}

seed().catch(console.error);
