export const seedCategories = [
  { name: "DevOps", slug: "devops", icon: "Settings" },
  { name: "Cloud Computing", slug: "cloud", icon: "Cloud" },
  { name: "Platform Engineering", slug: "platform-engineering", icon: "Layers" },
  { name: "Kubernetes", slug: "kubernetes", icon: "Box" },
  { name: "AI Engineering", slug: "ai-engineering", icon: "Cpu" },
  { name: "Cybersecurity", slug: "cybersecurity", icon: "Shield" },
  { name: "SRE", slug: "sre", icon: "Activity" },
  { name: "GitOps", slug: "gitops", icon: "GitBranch" },
  { name: "Linux", slug: "linux", icon: "Terminal" },
  { name: "Networking", slug: "networking", icon: "Globe" },
  { name: "CI/CD", slug: "cicd", icon: "Zap" },
  { name: "Monitoring", slug: "monitoring", icon: "BarChart2" },
];

export const monitoringResources = [
  {
    title: "Grafana – The Open Observability Platform",
    description: "Grafana is the leading open-source platform for monitoring and observability. Query, visualize, alert on and understand your metrics, logs, and traces with beautiful dashboards.",
    url: "https://grafana.com/",
    type: "documentation",
    category: "Monitoring",
    platform: "Grafana Labs",
    tags: "grafana,dashboards,observability,metrics,visualization",
    upvotes: 2100,
    isFree: true,
    rating: 5,
    isFeatured: true,
  },
  {
    title: "Prometheus – Monitoring System & Time Series DB",
    description: "Prometheus is an open-source systems monitoring and alerting toolkit. It collects and stores metrics as time series data, with powerful queries via PromQL.",
    url: "https://prometheus.io/docs/introduction/overview/",
    type: "documentation",
    category: "Monitoring",
    platform: "Prometheus",
    tags: "prometheus,metrics,alerting,time-series,promql",
    upvotes: 1950,
    isFree: true,
    rating: 5,
    isFeatured: true,
  },
  {
    title: "Grafana + Prometheus – Full Stack Monitoring Tutorial",
    description: "Complete guide to setting up a production-grade monitoring stack with Prometheus for metrics collection and Grafana for visualization and alerting.",
    url: "https://grafana.com/docs/grafana/latest/getting-started/get-started-grafana-prometheus/",
    type: "documentation",
    category: "Monitoring",
    platform: "Grafana Labs",
    tags: "grafana,prometheus,monitoring,tutorial,stack",
    upvotes: 1400,
    isFree: true,
    rating: 5,
  },
  {
    title: "AWS CloudWatch – Official Documentation",
    description: "Amazon CloudWatch is a monitoring and management service that provides data and actionable insights for AWS resources, applications, and services. Set alarms, log metrics, and more.",
    url: "https://docs.aws.amazon.com/cloudwatch/",
    type: "documentation",
    category: "Monitoring",
    platform: "AWS",
    tags: "aws,cloudwatch,logs,alarms,metrics,cloud-monitoring",
    upvotes: 1650,
    isFree: false,
    rating: 5,
  },
  {
    title: "Azure Monitor – Full Observability for Azure",
    description: "Azure Monitor collects, analyzes, and acts on telemetry from your Azure and on-premises environments. Includes Application Insights, Log Analytics, and more.",
    url: "https://learn.microsoft.com/en-us/azure/azure-monitor/overview",
    type: "documentation",
    category: "Monitoring",
    platform: "Microsoft Azure",
    tags: "azure,monitor,logs,metrics,application-insights,cloud",
    upvotes: 1300,
    isFree: false,
    rating: 4,
  },
  {
    title: "New Relic – Full-Stack Observability Platform",
    description: "New Relic provides full-stack observability for your entire software stack. Monitor APM, infrastructure, logs, browser, mobile, and synthetics from one platform.",
    url: "https://docs.newrelic.com/",
    type: "documentation",
    category: "Monitoring",
    platform: "New Relic",
    tags: "newrelic,apm,observability,tracing,logs,infrastructure",
    upvotes: 1200,
    isFree: false,
    rating: 4,
  },
  {
    title: "Zabbix – Enterprise-Class Monitoring",
    description: "Zabbix is a mature, enterprise-level platform designed to monitor networks, servers, cloud, applications, and services. Fully open source with no limits on hosts.",
    url: "https://www.zabbix.com/documentation/current/en/manual",
    type: "documentation",
    category: "Monitoring",
    platform: "Zabbix",
    tags: "zabbix,network-monitoring,server,snmp,enterprise,alerts",
    upvotes: 980,
    isFree: true,
    rating: 4,
  },
  {
    title: "Nagios – IT Infrastructure Monitoring",
    description: "Nagios is one of the most widely used open-source monitoring solutions. Monitor hosts, services, and network devices with powerful alerting and notification capabilities.",
    url: "https://www.nagios.org/documentation/",
    type: "documentation",
    category: "Monitoring",
    platform: "Nagios",
    tags: "nagios,infrastructure,alerts,network,plugins,host-monitoring",
    upvotes: 870,
    isFree: true,
    rating: 4,
  },
  {
    title: "Datadog – Cloud Monitoring as a Service",
    description: "Datadog is a monitoring and security platform for cloud applications. It brings together end-to-end traces, metrics, and logs, making your stack fully observable.",
    url: "https://docs.datadoghq.com/",
    type: "documentation",
    category: "Monitoring",
    platform: "Datadog",
    tags: "datadog,apm,logs,infrastructure,tracing,saas-monitoring",
    upvotes: 1550,
    isFree: false,
    rating: 5,
  },
  {
    title: "OpenTelemetry – Vendor-Neutral Observability Framework",
    description: "OpenTelemetry provides a collection of APIs, SDKs, and tools to instrument, generate, collect, and export telemetry data (metrics, logs, and traces).",
    url: "https://opentelemetry.io/docs/",
    type: "documentation",
    category: "Monitoring",
    platform: "OpenTelemetry",
    tags: "opentelemetry,otel,tracing,metrics,logs,vendor-neutral,cncf",
    upvotes: 1750,
    isFree: true,
    rating: 5,
    isFeatured: true,
  },
  {
    title: "Loki – Like Prometheus but for Logs",
    description: "Grafana Loki is a horizontally scalable, highly available, multi-tenant log aggregation system inspired by Prometheus. Designed to be cost-effective and easy to operate.",
    url: "https://grafana.com/docs/loki/latest/",
    type: "documentation",
    category: "Monitoring",
    platform: "Grafana Labs",
    tags: "loki,logs,log-aggregation,grafana,kubernetes",
    upvotes: 1100,
    isFree: true,
    rating: 4,
  },
  {
    title: "Jaeger – End-to-End Distributed Tracing",
    description: "Jaeger is an open-source, end-to-end distributed tracing system, used for monitoring microservices-based distributed systems. CNCF graduated project.",
    url: "https://www.jaegertracing.io/docs/",
    type: "documentation",
    category: "Monitoring",
    platform: "Jaeger / CNCF",
    tags: "jaeger,tracing,distributed-tracing,microservices,cncf",
    upvotes: 980,
    isFree: true,
    rating: 4,
  },
  {
    title: "Elastic Stack (ELK) – Search, Observe, Protect",
    description: "The Elastic Stack — Elasticsearch, Logstash, and Kibana — is the world's most popular log management platform. Collect, parse, and visualize any type of data.",
    url: "https://www.elastic.co/elastic-stack",
    type: "documentation",
    category: "Monitoring",
    platform: "Elastic",
    tags: "elk,elasticsearch,kibana,logstash,logs,search,observability",
    upvotes: 1800,
    isFree: true,
    rating: 5,
  },
  {
    title: "VictoriaMetrics – Fast & Scalable Monitoring",
    description: "VictoriaMetrics is a fast, cost-saving, and scalable monitoring solution and time series database. Drop-in replacement for Prometheus with better performance.",
    url: "https://docs.victoriametrics.com/",
    type: "documentation",
    category: "Monitoring",
    platform: "VictoriaMetrics",
    tags: "victoriametrics,prometheus,time-series,scalable,monitoring",
    upvotes: 760,
    isFree: true,
    rating: 4,
  },
  {
    title: "Google Cloud Monitoring (formerly Stackdriver)",
    description: "Google Cloud's operations suite provides monitoring, logging, and diagnostics for applications running on Google Cloud and beyond.",
    url: "https://cloud.google.com/monitoring/docs",
    type: "documentation",
    category: "Monitoring",
    platform: "Google Cloud",
    tags: "gcp,stackdriver,cloud-monitoring,logs,metrics,google-cloud",
    upvotes: 1050,
    isFree: false,
    rating: 4,
  },
];

export const seedResources = [
  {
    title: "The Roadmap to DevOps in 2024",
    description: "A comprehensive guide on how to become a DevOps engineer in 2024 with a clear learning path.",
    url: "https://roadmap.sh/devops",
    type: "documentation",
    category: "DevOps",
    platform: "Roadmap.sh",
    tags: "roadmap,learning,devops",
    upvotes: 1250,
    isFree: true,
    rating: 5,
    isFeatured: true,
  },
  {
    title: "Kubernetes Documentation",
    description: "Official documentation for Kubernetes orchestration system.",
    url: "https://kubernetes.io/docs/home/",
    type: "documentation",
    category: "Kubernetes",
    platform: "Kubernetes",
    tags: "k8s,orchestration,containers",
    upvotes: 850,
    isFree: true,
    rating: 5,
  },
  {
    title: "Awesome Platform Engineering",
    description: "A curated list of platform engineering resources, tools, and tutorials.",
    url: "https://github.com/platform-engineering-org/awesome-platform-engineering",
    type: "repository",
    category: "Platform Engineering",
    platform: "GitHub",
    tags: "platform,engineering,awesome",
    upvotes: 450,
    isFree: true,
    rating: 4,
  },
  {
    title: "AWS Workshops",
    description: "Self-paced labs and workshops for learning AWS services.",
    url: "https://workshops.aws/",
    type: "course",
    category: "Cloud Computing",
    platform: "AWS",
    tags: "aws,cloud,labs",
    upvotes: 620,
    isFree: true,
    rating: 5,
  },
  {
    title: "Hussein Nasser's Backend Engineering",
    description: "In-depth videos on backend engineering, networking, and cloud architecture.",
    url: "https://www.youtube.com/@hnasser",
    type: "video",
    category: "DevOps",
    platform: "YouTube",
    tags: "backend,networking,cloud",
    upvotes: 980,
    isFree: true,
    rating: 5,
    isFeatured: true,
  },
  {
    title: "Terraform Best Practices",
    description: "Guide on how to structure your Terraform projects for production.",
    url: "https://www.terraform-best-practices.com/",
    type: "documentation",
    category: "DevOps",
    platform: "Terraform",
    tags: "iac,terraform,infrastructure",
    upvotes: 340,
    isFree: true,
    rating: 4,
  },
  {
    title: "Google SRE Book",
    description: "The original Site Reliability Engineering book by Google engineers.",
    url: "https://sre.google/sre-book/table-of-contents/",
    type: "blog",
    category: "SRE",
    platform: "Google",
    tags: "sre,reliability,operations",
    upvotes: 1500,
    isFree: true,
    rating: 5,
    isFeatured: true,
  },
  {
    title: "LangChain Documentation",
    description: "Learn how to build LLM-powered applications.",
    url: "https://python.langchain.com/docs/get_started/introduction",
    type: "documentation",
    category: "AI Engineering",
    platform: "LangChain",
    tags: "ai,llm,python",
    upvotes: 720,
    isFree: true,
    rating: 4,
  },
  {
    title: "Docker Curriculum",
    description: "A comprehensive tutorial on getting started with Docker and containers.",
    url: "https://docker-curriculum.com/",
    type: "documentation",
    category: "DevOps",
    platform: "Docker Curriculum",
    tags: "docker,containers,beginner",
    upvotes: 890,
    isFree: true,
    rating: 5,
  },
  {
    title: "Full Stack Open - CI/CD",
    description: "A great course on CI/CD pipelines, GitHub Actions, and deployment.",
    url: "https://fullstackopen.com/en/part11",
    type: "course",
    category: "GitOps",
    platform: "University of Helsinki",
    tags: "cicd,github-actions,automation",
    upvotes: 1100,
    isFree: true,
    rating: 5,
  },
  {
    title: "Cloud Native Computing Foundation (CNCF) Landscape",
    description: "The complete map of the cloud native ecosystem.",
    url: "https://landscape.cncf.io/",
    type: "documentation",
    category: "Cloud Computing",
    platform: "CNCF",
    tags: "cloud-native,landscape,k8s",
    upvotes: 430,
    isFree: true,
    rating: 4,
  },
  {
    title: "The Linux Command Line",
    description: "A complete introduction to the Linux shell and command line.",
    url: "https://linuxcommand.org/",
    type: "documentation",
    category: "DevOps",
    platform: "LinuxCommand.org",
    tags: "linux,bash,shell",
    upvotes: 1200,
    isFree: true,
    rating: 5,
  },
  {
    title: "AWS Announces New Generative AI Capabilities for Amazon Bedrock",
    description: "Amazon Bedrock now includes new models and features to help customers build and scale generative AI applications more easily.",
    url: "https://aws.amazon.com/blogs/aws/new-generative-ai-capabilities-for-amazon-bedrock/",
    type: "news",
    category: "AI Engineering",
    platform: "AWS Blog",
    author: "Jeff Barr",
    tags: "aws,ai,bedrock",
    upvotes: 450,
  },
  {
    title: "Kubernetes 1.30: Uwubernetes",
    description: "The latest release of Kubernetes brings enhancements to structured logging, node memory swapping, and more.",
    url: "https://kubernetes.io/blog/2024/04/17/kubernetes-v1-30-release/",
    type: "news",
    category: "Kubernetes",
    platform: "Kubernetes Blog",
    author: "Release Team",
    tags: "k8s,release",
    upvotes: 890,
  },
  {
    title: "Terraform 1.8 Adds Provider-Defined Functions",
    description: "HashiCorp announces Terraform 1.8 with a major new feature: functions defined by providers.",
    url: "https://www.hashicorp.com/blog/terraform-1-8-adds-provider-defined-functions",
    type: "news",
    category: "DevOps",
    platform: "HashiCorp Blog",
    author: "Terraform Team",
    tags: "terraform,iac",
    upvotes: 670,
  },
  {
    title: "Google Cloud introduces AI-powered security operations",
    description: "New capabilities in Google Cloud Security Operations use generative AI to help security teams detect and respond to threats faster.",
    url: "https://cloud.google.com/blog/products/identity-security/introducing-ai-powered-security-operations",
    type: "news",
    category: "Cybersecurity",
    platform: "Google Cloud Blog",
    author: "Security Team",
    tags: "gcp,security,ai",
    upvotes: 320,
  },
  {
    title: "Microsoft Azure announces Cobalt 100 CPUs for general availability",
    description: "Azure's first custom-built processors are now available for customers, offering better price-performance for cloud workloads.",
    url: "https://azure.microsoft.com/en-us/blog/azure-cobalt-100-cpus-now-generally-available/",
    type: "news",
    category: "Cloud Computing",
    platform: "Azure Blog",
    author: "Azure Team",
    tags: "azure,hardware,cloud",
    upvotes: 510,
  },
  {
    title: "Docker Desktop 4.30 includes Docker Build Cloud integration",
    description: "The latest version of Docker Desktop makes it easier to use remote build capabilities for faster container image creation.",
    url: "https://www.docker.com/blog/docker-desktop-4-30-docker-build-cloud/",
    type: "news",
    category: "DevOps",
    platform: "Docker Blog",
    author: "Docker Team",
    tags: "docker,containers",
    upvotes: 410,
  },
  {
    title: "OpenAI launches SearchGPT, a prototype of new AI search features",
    description: "OpenAI is testing a new AI-powered search engine that aims to give users fast and timely answers with clear and relevant sources.",
    url: "https://openai.com/index/searchgpt-prototype/",
    type: "news",
    category: "AI Engineering",
    platform: "OpenAI Blog",
    author: "OpenAI",
    tags: "ai,search,searchgpt",
    upvotes: 1200,
  },
  {
    title: "The Case for Platform Engineering in 2024",
    description: "Why organizations are moving away from traditional DevOps towards internal developer platforms.",
    url: "https://techcrunch.com/2024/05/20/platform-engineering-is-the-new-devops/",
    type: "news",
    category: "Platform Engineering",
    platform: "TechCrunch",
    author: "Ron Miller",
    tags: "platform-engineering,devops",
    upvotes: 950,
  },
  {
    title: "Anthropic's Claude 3.5 Sonnet sets new industry benchmarks",
    description: "The latest model from Anthropic outperforms competitors in coding, reasoning, and visual processing tasks.",
    url: "https://www.anthropic.com/news/claude-3-5-sonnet",
    type: "news",
    category: "AI Engineering",
    platform: "Anthropic",
    author: "Anthropic Team",
    tags: "ai,llm,claude",
    upvotes: 1500,
  },
];
